### ISSUE TITLE
Stackoverflow "BOMB" after any unhandled exception 

### ISSUE THREAD

**Issue by bakomchik** [vy/log4j2-logstash-layout#28]
Hi guys!
recently i ran into problem , i got StackOverflowError and a lot of JsonGenerationException.
`java.lang.StackOverflowError
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)
	at com.fasterxml.jackson.core.filter.TokenFilterContext._writePath(TokenFilterContext.java:213)`

After some investigation i found that after any non JsonGenerationException state of JsonGenerator become corrupted and after while leads to StackOverflowError.
I  wrote test to demonstrate case, just follow the link https://github.com/bakomchik/log4j2-logstash-layout/commit/f933ba02841cd323375cbd176b26bfdc271117c5 
I 've already made pull request.
https://github.com/vy/log4j2-logstash-layout/pull/27

**Comment by vy** [comment]
Thanks for the fantastic report @bakomchik! I will check it out sometime this week and act on it.

**Comment by vy** [comment]
I am closing this ticket and use #27 instead.
