### ISSUE TITLE
BufferOverflowException get thrown for messages of a larger size

### ISSUE THREAD

**Issue by mzeijen** [vy/log4j2-logstash-layout#50]
We have seen for many instances that the `1.0.0` version has a problem with messages of a larger size. It starts throwing BufferOverflowException exceptions when a certain threshold is reached. The exception that is logged to the console is as follows:

```
AsyncAppender-REDIS_GENERAL_LOG_ASYNC ERROR An exception occurred processing Appender REDIS_GENERAL_LOG java.lang.RuntimeException: failed serializing JSON
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.toByteArray(LogstashLayout.java:213)
	at com.vlkan.log4j2.redis.appender.RedisAppender.append(RedisAppender.java:138)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.appender.AsyncAppender$AsyncThread.callAppenders(AsyncAppender.java:454)
	at org.apache.logging.log4j.core.appender.AsyncAppender$AsyncThread.run(AsyncAppender.java:407)
Caused by: java.nio.BufferOverflowException
	at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:225)
	at com.vlkan.log4j2.logstash.layout.util.ByteBufferOutputStream.write(ByteBufferOutputStream.java:48)
	at com.vlkan.log4j2.logstash.layout.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2137)
	at com.vlkan.log4j2.logstash.layout.jackson.core.json.UTF8JsonGenerator._writeStringSegment2(UTF8JsonGenerator.java:1413)
	at com.vlkan.log4j2.logstash.layout.jackson.core.json.UTF8JsonGenerator._writeStringSegment(UTF8JsonGenerator.java:1366)
	at com.vlkan.log4j2.logstash.layout.jackson.core.json.UTF8JsonGenerator._writeStringSegments(UTF8JsonGenerator.java:1307)
	at com.vlkan.log4j2.logstash.layout.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:574)
	at com.vlkan.log4j2.logstash.layout.resolver.StackTraceTextResolver.resolve(StackTraceTextResolver.java:43)
	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionRootCauseResolver$1.lambda$createStackTraceTextResolver$2(ExceptionRootCauseResolver.java:71)
	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionRootCauseResolver.resolve(ExceptionRootCauseResolver.java:103)
	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionRootCauseResolver.resolve(ExceptionRootCauseResolver.java:26)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:146)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:146)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:146)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:262)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.toByteArray(LogstashLayout.java:209)
```

I am not sure what the exact size is when this starts the happen. But testing with by increasing the message size has shown me that these exceptions starts the occur when the message contains +-15.700 characters. I believe the issue occurs when the total size of the serialised json data is getting to be, and that it is not specific to the message. We see these BufferOverflowException exceptions as well when a MDC field contains a large amount of data.

When reverting back to 0.21 we don't see this issue anymore

**Comment by mzeijen** [comment]
Ok, while looking at the readme change for 1.0.0 I now see that `maxByteCount` has been reduced from 512 KiB to 16 KiB. 

Is this what causes the BufferOverflowExceptions?

**Comment by vy** [comment]
Yep, `BOE` is probably due to the decreased `maxByteCount`. Bumping it back to 512 KiB should solve your problems. Additionally, note that 1.0.0 has switched back to thread-local allocations (TLA). For the optimal efficiency, make sure it is enabled by setting `log4j2.enable.threadlocals=true` and `log4j2.is.webapp=false` properties.

**Comment by felixbarny** [comment]
> For the optimal efficiency, make sure it is enabled by setting log4j2.enable.threadlocals=true and log4j2.is.webapp=false properties.

Note that this causes classloader leaks when un/re-deploying web applications.

**Comment by vy** [comment]
@mzeijen, you might also consider truncating excessive fields via `maxStringLength` directive.

**Comment by mzeijen** [comment]
@vy The question then is what an excessive length is... The same with the number of bytes. 16 KiB is clearly too small but is 512 KiB to big?

**Comment by sebthom** [comment]
@mzeijen wouldn't it makes sense to catch the BufferOverflowException in toByteArray and throw another exception with a more descriptive message (pointing to maxByteCount) or don't throw another exception but simply log the error message without stacktrace?

**Comment by vy** [comment]
@mzeijen, `LogstashLayout` performs TLAs that are of worth consideration in two places:

1. While generating the JSON payload (string fields are capped by `maxStringLength` and total length is capped by `maxByteCount`)
2.  While converting stack traces to text (total length is again capped by `maxByteCount`)

This leads to the following formula for the plugin's memory consumption:

```
threadCount * (
    (stackTraceEnabled ? 1 : 0) * maxByteCount +    // for stacktraces
    maxByteCount +    // for JSON
    epsilon    // for the rest
)
```

Here `epsilon` is <100 bytes. (This depends on certain things: timestamp length, do you use doubles, etc.)

I am closing the issue. Don't hesitate to re-open it if you have any further questions.
