### ISSUE TITLE
Nullpointer exceptions at LogstashLayoutSerializationContexts$StringTruncatingGeneratorDelegate 

### ISSUE THREAD

**Issue by mzeijen** [vy/log4j2-logstash-layout#53]
We see Nullpointer exceptions with the following stack trace:

```
 AsyncAppender-REDIS_GENERAL_LOG_ASYNC ERROR An exception occurred processing Appender REDIS_GENERAL_LOG java.lang.RuntimeException: failed serializing JSON
 	at com.vlkan.log4j2.logstash.layout.LogstashLayout.toByteArray(LogstashLayout.java:213)
 	at com.vlkan.log4j2.redis.appender.RedisAppender.append(RedisAppender.java:138)
 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
 	at org.apache.logging.log4j.core.appender.AsyncAppender$AsyncThread.callAppenders(AsyncAppender.java:454)
 	at org.apache.logging.log4j.core.appender.AsyncAppender$AsyncThread.run(AsyncAppender.java:407)
 Caused by: java.lang.NullPointerException
 	at com.vlkan.log4j2.logstash.layout.LogstashLayoutSerializationContexts$StringTruncatingGeneratorDelegate.writeString(LogstashLayoutSerializationContexts.java:128)
 	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionResolver$1.lambda$createMessageResolver$1(ExceptionResolver.java:51)
 	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionResolver.resolve(ExceptionResolver.java:98)
 	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionResolver.resolve(ExceptionResolver.java:25)
 	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:146)
 	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:146)
 	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:146)
 	at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:262)
 	at com.vlkan.log4j2.logstash.layout.LogstashLayout.toByteArray(LogstashLayout.java:209)
 	... 7 more
```

If the `StringTruncatingGeneratorDelegate#writeString` method gets a null then it fails on the first if check, as it tries to call `length` on a `null` reference: 

```
if (maxStringLength <= 0 || maxStringLength >= text.length()) {
    super.writeString(text);
} else {
    StringReader textReader = new StringReader(text);
    super.writeString(textReader, maxStringLength);
}
```
It can get the `null` value from the `ExceptionResolver` when  `emptyPropertyExclusionEnabled` is not set to `true`, which is the default. 

I am not sure if this should be fixed in this write method or it needs to be fixed at the call sites of this method.

**Comment by vy** [comment]
Doh! :man_facepalming: We better fix it in `StringTruncatingGeneratorDelegate#writeString` rather than all potential call sites. I have just released v1.0.1 with the fix (incl. test!) and it should momentarily show up in Maven Central repos. Thanks so much for the report.
