### ISSUE TITLE
Failed serializing JSON: BufferOverflowException

### ISSUE THREAD

**Issue by ilgrosso** [vy/log4j2-logstash-layout#58]
Getting the exception below with GCP (using template from #54), version 1.0.2:

```
Log4j2-TF-1-AsyncLoggerConfig-1 ERROR An exception occurred processing Appender mainFile java.lang.RuntimeException: failed serializing JSON
 at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:230)
 at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:57)
 at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:197)
[...]
 Caused by: java.nio.BufferOverflowException
 at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:194)
 at com.vlkan.log4j2.logstash.layout.util.ByteBufferOutputStream.write(ByteBufferOutputStream.java:48)
 at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2137)
 at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1150)
 at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:263)
 at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:221)
 ... 19 more
```

**Comment by vy** [comment]
Your payload exceeds the `maxByteCount` limit. You better tune that. Also check out `maxStringLength` configuration.

**Comment by ilgrosso** [comment]
Thanks for your answer @vy 

Would the following conf work, then?

```json
{
  "mdc1": "${json:mdc:key1}",
  "mdc2": "${json:mdc:key2}",
  "mdc3": "${json:mdc:key3}",
  "timestamp": "${json:timestamp}",
  "severity": "${json:level}",
  "thread": "${json:thread:name}",
  "logger": "${json:logger:name}",
  "message": "${json:message}",
  "exception": "${json:exception:stackTrace:text}",
  "logging.googleapis.com/trace": "${json:mdc:X-B3-TraceId}",
  "serviceContext": "${json:mdc:serviceContext}",
  "maxByteCount": 4096,
  "maxStringLength": 4096
}
```

**Comment by vy** [comment]
@ilgrosso, no, you need to provide those to `LogstashLayout` configuration, not integrate them into the template:

```xml
<LogstashLayout ... maxByteCount=4096 maxStringLength=4096/>
```

As a side note, 4 KiB (i.e., 4096) is pretty low for `maxByteCount`. This might easily get violated when you try to render a stack trace.

**Comment by ilgrosso** [comment]
Thanks @vy I will then set something like

```xml
      <LogstashLayout dateTimeFormatPattern="yyyy-MM-dd'T'HH:mm:ss.SSSZZZ"
                      timeZoneId="UTC"
                      eventTemplateUri="file:/opt/syncope/conf/logstashGCP.json"
                      prettyPrintEnabled="false"
                      maxByteCount="65536" maxStringLength="65536"
                      stackTraceEnabled="true"/>
```

I hope 64Kb will be enough.

**Comment by vy** [comment]
16 KiB for `maxByteCount` and 8 KiB for `maxStringLength` should be sufficient. If there is still a `LogEvent` that exceeds these limits, it is better for it to get dropped.

**Comment by ilgrosso** [comment]
Thanks again!

**Comment by ilgrosso** [comment]
@vy it appears that 16 Kb is the default for `maxByteCount`: https://github.com/vy/log4j2-logstash-layout/blob/master/layout/src/main/java/com/vlkan/log4j2/logstash/layout/LogstashLayout.java#L349

Since I am getting the exception reported above I think I'll need to set some more space.

**Comment by james-r-smith** [comment]
@vy, not sure whether to open another ticket or not (will do if you need me to), but I'm facing an issue that is **very** closely related to this. The only difference is that I'm using `exception:stackTrace` and not `exception:stackTrace:text`. With this configured, `maxStringLength` and `maxByteCount` give me the ability to print out the exception, but not truncate it if it's too long (essentially, I'm looking for a more failsafe option than throwing the exception below if the buffer isn't big enough). I ran into this problem when I hit a nasty long Hibernate exception (greater than 16kb `maxByteCount` 😵 ). Wondering if there could be better way to handle the exception for the JSON stack trace (similar to string truncation, where an exception isn't thrown). Currently, I've fallen back to using `exception:stackTrace:text`.

```
2020-07-20 21:51:10,527 http-nio-8080-exec-9 ERROR An exception occurred processing Appender Console java.lang.RuntimeException: failed serializing JSON
        at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:230)
        at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:57)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:197)
[...]
Caused by: java.nio.BufferOverflowException
        at java.base/java.nio.HeapByteBuffer.put(Unknown Source)
        at com.vlkan.log4j2.logstash.layout.util.ByteBufferOutputStream.write(ByteBufferOutputStream.java:48)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2159)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1173)
        at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:263)
        at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:221)
        ... 39 more
```

**Comment by vy** [comment]
@james-r-smith, unfortunately there is not much `LogstashLayout` can do here -- let me know if you have any proposals. Consider somebody injecting an MDC field of type array where there are 1e6 strings each less than `maxStringLength`. This as well will hit to the `maxByteCount` wall. Could decreasing `-XX:MaxJavaStackTraceDepth` be an option for you?

What else I can do is to provide a `maxArrayLength` parameter -- though this will indeed need a new ticket.

**Comment by james-r-smith** [comment]
Hey @vy. Great suggestions 😊 I like the `-XX:MaxJavaStackTraceDepth` option as well as the potential `maxArrayLength` parameter. For right now, I've also been liking the stack trace string. I chose this library in our project because of it's near-future addition to Log4J3. Will this also be something which will occur once implemented there as well? If so, would I file a ticket in both libraries? Just need some idea if this library will be fully migrated/maintained in Log4J3 once released, deprecating this library. 🤔  Awesome work on this project! Really appreciate the hard work put into this library.
