### ISSUE TITLE
Multiple template variables in single property lead to an exception

### ISSUE THREAD

**Issue by Fleshgrinder** [vy/log4j2-logstash-layout#63]
I wanted to use multiple template variables in a single property:

```json
{
  // snip
  "caller": "${json:source:className}.${json:source:methodName}",
  "file": "${json:source:fileName}#${json:source:lineNumber}"
}
```

The problem is that I'm presented with an exception upon startup:

```
2020-07-29 18:55:18,959 main ERROR Could not create plugin of type class com.vlkan.log4j2.logstash.layout.LogstashLayout for element LogstashLayout: java.lang.IllegalArgumentException: unknown key: className}.${json:source:methodName java.lang.IllegalArgumentException: unknown key: className}.${json:source:methodName
	at com.vlkan.log4j2.logstash.layout.resolver.SourceResolver.createInternalResolver(SourceResolver.java:45)
	at com.vlkan.log4j2.logstash.layout.resolver.SourceResolver.<init>(SourceResolver.java:32)
	at com.vlkan.log4j2.logstash.layout.resolver.SourceResolverFactory.create(SourceResolverFactory.java:36)
	at com.vlkan.log4j2.logstash.layout.resolver.SourceResolverFactory.create(SourceResolverFactory.java:19)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.ofStringNode(TemplateResolvers.java:168)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.ofNode(TemplateResolvers.java:80)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.ofObjectNode(TemplateResolvers.java:127)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.ofNode(TemplateResolvers.java:79)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.ofTemplate(TemplateResolvers.java:69)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.createEventResolver(LogstashLayout.java:153)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.<init>(LogstashLayout.java:85)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.<init>(LogstashLayout.java:61)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout$Builder.build(LogstashLayout.java:547)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout$Builder.build(LogstashLayout.java:297)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at com.fleshgrinder.logging.LoggingKt.main(Logging.kt:6)
	at com.fleshgrinder.logging.LoggingKt.main(Logging.kt)

2020-07-29 18:55:18,960 main ERROR Unable to invoke factory method in class com.vlkan.log4j2.logstash.layout.LogstashLayout for element LogstashLayout: java.lang.IllegalStateException: No factory method found for class com.vlkan.log4j2.logstash.layout.LogstashLayout java.lang.IllegalStateException: No factory method found for class com.vlkan.log4j2.logstash.layout.LogstashLayout
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:234)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at com.fleshgrinder.logging.LoggingKt.main(Logging.kt:6)
	at com.fleshgrinder.logging.LoggingKt.main(Logging.kt)

test message
```

The moment I reduce the line to a single template variables things work as usual, however, I would expect this to work. 😊 

PS: Thanks for the great library and your efforts to get it into core. ❤️

**Comment by vy** [comment]
@Fleshgrinder That is not supported by `LogstashLayout`. See the following section in the docs:

> ... note that ... `${json:...}` template variables are expected to occupy an entire field, that is, "level": "${json:level}", ...

You might have noticed that I am busy with integrating `LogstashLayout` into Log4j core under the name `JsonTemplateLayout`, see #60. There you will be able to do what you want by inject a `PatternLayout` into your JSON template:

```json
{
  "caller": {
    "$resolver": "pattern",
    "pattern": "%class.%method"
  },
  "file": {
    "$resolver": "pattern",
    "pattern": "%file:%line"
  }
}
```

Just a bit more patience, please. :wink:

Do you need it *right now* or can you wait for 1-2 months?

**Comment by Fleshgrinder** [comment]
I didn’t notice that in the README (you know how it is sometimes, you read it but your brain directly discards it).

> Just a bit more patience, please. 😉
Nullo problemlo

> Do you need it _right now_ or can you wait for 1-2 months?
You’d have a PR instead of an issue if I’d be desperate. 😉 Go on, concentrate on getting it into core, and once more, thanks for your hard work. ❤️ 

PS: Feel free to close the issue, I would leave it open for others though. It can act as a nice pointer to the core integration including an “official” statement that it will be supported there.
