### ISSUE TITLE
NoClassDefFoundError: logstash.layout.resolver.TemplateResolvers (initialization failure)

### ISSUE THREAD

**Issue by ramazanpolat** [vy/log4j2-logstash-layout#65]
Hi, I'm getting the following error when I use Logstash Layout.
The project is not a maven project but so I put the jar files manually.

Any idea why this happens?

java.lang.NoClassDefFoundError: com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers (initialization failure)

Full log:
```
[10/1/20 14:39:01:791 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,791 WebContainer : 1 INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
[10/1/20 14:39:01:795 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,795 WebContainer : 1 DEBUG Closing BufferedInputStream java.io.BufferedInputStream@40edbe51
[10/1/20 14:39:01:802 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,802 WebContainer : 1 DEBUG Apache Log4j Core 2.13.3 initializing configuration XmlConfiguration[location=/Was/IBM/WebSphere/AppServer/profiles/AppSrv01/installedApps/MYSERVER019Cell01/MyWebAppX.ear/MyWebAppX.war/WEB-INF/classes/log4j2.xml]
[10/1/20 14:39:01:803 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,803 WebContainer : 1 DEBUG Installed 1 script engine
[10/1/20 14:39:01:821 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,821 WebContainer : 1 DEBUG Oracle Nashorn version: 1.8.0, language: ECMAScript, threading: Not Thread Safe, compile: true, names: [nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript], factory class: jdk.nashorn.api.scripting.NashornScriptEngineFactory
[10/1/20 14:39:01:822 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,822 WebContainer : 1 DEBUG PluginManager 'Core' found 125 plugins
[10/1/20 14:39:01:823 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,823 WebContainer : 1 DEBUG PluginManager 'Level' found 0 plugins
[10/1/20 14:39:01:826 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,825 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:827 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,826 WebContainer : 1 DEBUG createProperty(name="filead", value="/Was/sgk/logs/MyWebAppX/MyWebAppX")
[10/1/20 14:39:01:827 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,827 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:828 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,828 WebContainer : 1 DEBUG createProperty(name="env", value="test")
[10/1/20 14:39:01:828 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,828 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:829 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,829 WebContainer : 1 DEBUG createProperty(name="app", value="muhtasar")
[10/1/20 14:39:01:830 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,830 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:831 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,830 WebContainer : 1 DEBUG createProperty(name="module", value="gib")
[10/1/20 14:39:01:831 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,831 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:832 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,832 WebContainer : 1 DEBUG createProperty(name="appPassword", value="123")
[10/1/20 14:39:01:833 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,832 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:833 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,833 WebContainer : 1 DEBUG createProperty(name="kafkaVisioAdres", value="kafka1.intra:9092,kafka2.intra:9092,kafka3.intra:9092")
[10/1/20 14:39:01:834 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,834 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:835 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,834 WebContainer : 1 DEBUG createProperty(name="visologVersion", value="2")
[10/1/20 14:39:01:835 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,835 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:836 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,836 WebContainer : 1 DEBUG createProperty(name="locationInfoEnabled", value="true")
[10/1/20 14:39:01:836 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,836 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:837 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,837 WebContainer : 1 DEBUG createProperty(name="stackTraceEnabled", value="true")
[10/1/20 14:39:01:838 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,838 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:838 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,838 WebContainer : 1 DEBUG createProperty(name="syncSend", value="true")
[10/1/20 14:39:01:839 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,839 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:840 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,839 WebContainer : 1 DEBUG createProperty(name="acks", value="all")
[10/1/20 14:39:01:840 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,840 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:841 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,841 WebContainer : 1 DEBUG createProperty(name="retention1", value="2688")
[10/1/20 14:39:01:841 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,841 WebContainer : 1 DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
[10/1/20 14:39:01:842 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,842 WebContainer : 1 DEBUG createProperty(name="timeZoneId", value="Asia/Istanbul")
[10/1/20 14:39:01:843 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,842 WebContainer : 1 DEBUG Building Plugin[name=properties, class=org.apache.logging.log4j.core.config.PropertiesPlugin].
[10/1/20 14:39:01:843 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,843 WebContainer : 1 DEBUG configureSubstitutor(={filead=/Was/sgk/logs/MyWebAppX/MyWebAppX, env=test, app=muhtasar, module=gib, appPassword=123, kafkaVisioAdres=kafka1.intra:9092,kafka2.intra:9092,kafka3.intra:9092, visologVersion=2, locationInfoEnabled=true, stackTraceEnabled=true, syncSend=true, acks=all, retention1=2688, timeZoneId=Asia/Istanbul}, Configuration(/Was/IBM/WebSphere/AppServer/profiles/AppSrv01/installedApps/MYSERVER019Cell01/MyWebAppX.ear/MyWebAppX.war/WEB-INF/classes/log4j2.xml))
[10/1/20 14:39:01:844 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,844 WebContainer : 1 DEBUG PluginManager 'Lookup' found 16 plugins
[10/1/20 14:39:01:847 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,847 WebContainer : 1 DEBUG Building Plugin[name=KeyValuePair, class=org.apache.logging.log4j.core.util.KeyValuePair].
[10/1/20 14:39:01:847 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,847 WebContainer : 1 DEBUG KeyValuePair$Builder(key="retention1", value="2688")
[10/1/20 14:39:01:848 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,848 WebContainer : 1 DEBUG Building Plugin[name=KeyValuePair, class=org.apache.logging.log4j.core.util.KeyValuePair].
[10/1/20 14:39:01:849 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,849 WebContainer : 1 DEBUG KeyValuePair$Builder(key="app", value="muhtasar")
[10/1/20 14:39:01:849 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,849 WebContainer : 1 DEBUG Building Plugin[name=KeyValuePair, class=org.apache.logging.log4j.core.util.KeyValuePair].
[10/1/20 14:39:01:850 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,850 WebContainer : 1 DEBUG KeyValuePair$Builder(key="module", value="gib")
[10/1/20 14:39:01:850 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,850 WebContainer : 1 DEBUG Building Plugin[name=KeyValuePair, class=org.apache.logging.log4j.core.util.KeyValuePair].
[10/1/20 14:39:01:851 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,850 WebContainer : 1 DEBUG KeyValuePair$Builder(key="visologVersion", value="2")
[10/1/20 14:39:01:851 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,851 WebContainer : 1 DEBUG Building Plugin[name=KeyValuePair, class=org.apache.logging.log4j.core.util.KeyValuePair].
[10/1/20 14:39:01:852 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,852 WebContainer : 1 DEBUG KeyValuePair$Builder(key="env", value="test")
[10/1/20 14:39:01:852 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,852 WebContainer : 1 DEBUG Building Plugin[name=EventTemplateAdditionalFields, class=com.vlkan.log4j2.logstash.layout.LogstashLayout$EventTemplateAdditionalFields].
[10/1/20 14:39:01:852 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,852 WebContainer : 1 DEBUG LogstashLayout$EventTemplateAdditionalFields$Builder(={retention1=2688, app=muhtasar, module=gib, visologVersion=2, env=test})
[10/1/20 14:39:01:853 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,853 WebContainer : 1 DEBUG Building Plugin[name=layout, class=com.vlkan.log4j2.logstash.layout.LogstashLayout].
[10/1/20 14:39:01:854 TRT] 000000c5 SystemOut     O 2020-10-01 14:39:01,854 WebContainer : 1 DEBUG LogstashLayout$Builder(Configuration(/Was/IBM/WebSphere/AppServer/profiles/AppSrv01/installedApps/MYSERVER019Cell01/MyWebAppX.ear/MyWebAppX.war/WEB-INF/classes/log4j2.xml), prettyPrintEnabled="false", locationInfoEnabled="true", stackTraceEnabled="true", emptyPropertyExclusionEnabled="true", dateTimeFormatPattern="yyyy-MM-dd'T'HH:mm:ssZZZ", timeZoneId="Asia/Istanbul", locale="null", eventTemplate="null", eventTemplateUri="classpath:visologEventLayout.json", EventTemplateAdditionalFields(com.vlkan.log4j2.logstash.layout.LogstashLayout$EventTemplateAdditionalFields@8607a1f9), stackTraceElementTemplate="null", stackTraceElementTemplateUri="null", mdcKeyPattern="null", ndcPattern="null", lineSeparator="null", maxByteCount="32768", maxStringLength="null", objectMapperFactoryMethod="null", mapMessageFormatterIgnored="null")
[10/1/20 14:39:01:865 TRT] 000000c5 AxisEngine    E org.apache.axis2.engine.AxisEngine receive null
                                 org.apache.axis2.AxisFault
	at org.apache.axis2.jaxws.server.dispatcher.JavaBeanDispatcher.createFaultResponse(JavaBeanDispatcher.java:407)
	at org.apache.axis2.jaxws.server.dispatcher.JavaBeanDispatcher.invoke(JavaBeanDispatcher.java:138)
	at org.apache.axis2.jaxws.server.EndpointController.invoke(EndpointController.java:111)
	at org.apache.axis2.jaxws.server.JAXWSMessageReceiver.receive(JAXWSMessageReceiver.java:161)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:212)
	at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:172)
	at com.ibm.ws.websvcs.transport.http.WASAxis2Servlet.doPost(WASAxis2Servlet.java:1633)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1124)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:963)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:289)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.axis2.jaxws.server.dispatcher.JavaDispatcher.invokeTargetOperation(JavaDispatcher.java:120)
	at org.apache.axis2.jaxws.server.dispatcher.JavaBeanDispatcher.invoke(JavaBeanDispatcher.java:118)
	... 30 more
Caused by: java.lang.NoClassDefFoundError: com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers (initialization failure)
	at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:96)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.createStackTraceElementResolver(LogstashLayout.java:121)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.<init>(LogstashLayout.java:83)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.<init>(LogstashLayout.java:61)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout$Builder.build(LogstashLayout.java:547)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout$Builder.build(LogstashLayout.java:297)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:602)
	at tr.gov.sgk.bildirge.webservice.business.PaketIslem.paketIptalSGK(PaketIslem.java:251)
	at tr.gov.sgk.bildirge.webservice.BildirgeWS.paketIptal(BildirgeWS.java:316)
	... 36 more
Caused by: java.lang.BootstrapMethodError: java.lang.LinkageError: loading constraint violation when overriding method "com/vlkan/log4j2/logstash/layout/resolver/TemplateResolver.resolve(Ljava/lang/Object;Lcom/fasterxml/jackson/core/JsonGenerator;)V" during creation of class "com/vlkan/log4j2/logstash/layout/resolver/TemplateResolvers$$Lambda$262/0000000008AB1080": loader "java/lang/InternalAnonymousClassLoader@e3c90ee7" of class "com/vlkan/log4j2/logstash/layout/resolver/TemplateResolvers$$Lambda$262/0000000008AB1080" and loader "com/ibm/ws/classloader/CompoundClassLoader@90ee7c7b" of class "com/vlkan/log4j2/logstash/layout/resolver/TemplateResolver" have different types for the method signature
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.<clinit>(TemplateResolvers.java:34)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.createStackTraceElementResolver(LogstashLayout.java:121)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.<init>(LogstashLayout.java:83)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.<init>(LogstashLayout.java:61)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout$Builder.build(LogstashLayout.java:547)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout$Builder.build(LogstashLayout.java:297)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.core.LoggerContext.getContext(LoggerContext.java:224)
	at tr.gov.sgk.util.sistem.SistemSabitDegerler.log4j2Islemleri(SistemSabitDegerler.java:94)
	at tr.gov.sgk.util.sistem.SistemSabitDegerler.<init>(SistemSabitDegerler.java:69)
	at tr.gov.sgk.bildirge.webservice.util.StartServlet.init(StartServlet.java:44)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:342)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.init(ServletWrapperImpl.java:169)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.loadOnStartupCheck(ServletWrapper.java:1376)
	at com.ibm.ws.webcontainer.webapp.WebApp.doLoadOnStartupActions(WebApp.java:673)
	at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationFinally(WebApp.java:639)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:454)
	at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:88)
	at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:171)
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:904)
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:789)
	at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:427)
	at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:719)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1249)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1590)
	at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:707)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:1161)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:801)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplicationDynamically(ApplicationMgrImpl.java:1451)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2319)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:436)
	at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:379)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:127)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$1.run(CompositionUnitMgrImpl.java:654)
	at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5536)
	at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5662)
	at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCompositionUnit(CompositionUnitMgrImpl.java:668)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCompositionUnit(CompositionUnitMgrImpl.java:612)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:1341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:83)
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:287)
	at javax.management.modelmbean.RequiredModelMBean$4.run(RequiredModelMBean.java:1263)
	at java.security.AccessController.doPrivileged(AccessController.java:664)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:91)
	at javax.management.modelmbean.RequiredModelMBean.invokeMethod(RequiredModelMBean.java:1257)
	at javax.management.modelmbean.RequiredModelMBean.invoke(RequiredModelMBean.java:1096)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:831)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:813)
	at com.ibm.ws.management.AdminServiceImpl$1.run(AdminServiceImpl.java:1350)
	at com.ibm.ws.security.util.AccessController.doPrivileged(AccessController.java:118)
	at com.ibm.ws.management.AdminServiceImpl.invoke(AdminServiceImpl.java:1243)
	at com.ibm.ws.management.connector.AdminServiceDelegator.invoke(AdminServiceDelegator.java:181)
	at com.ibm.ws.management.connector.ipc.CallRouter.route(CallRouter.java:247)
	at com.ibm.ws.management.connector.ipc.IPCConnectorInboundLink.doWork(IPCConnectorInboundLink.java:360)
	at com.ibm.ws.management.connector.ipc.IPCConnectorInboundLink$IPCConnectorReadCallback.complete(IPCConnectorInboundLink.java:602)
	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833)
	... 8 more
Caused by: java.lang.LinkageError: loading constraint violation when overriding method "com/vlkan/log4j2/logstash/layout/resolver/TemplateResolver.resolve(Ljava/lang/Object;Lcom/fasterxml/jackson/core/JsonGenerator;)V" during creation of class "com/vlkan/log4j2/logstash/layout/resolver/TemplateResolvers$$Lambda$262/0000000008AB1080": loader "java/lang/InternalAnonymousClassLoader@e3c90ee7" of class "com/vlkan/log4j2/logstash/layout/resolver/TemplateResolvers$$Lambda$262/0000000008AB1080" and loader "com/ibm/ws/classloader/CompoundClassLoader@90ee7c7b" of class "com/vlkan/log4j2/logstash/layout/resolver/TemplateResolver" have different types for the method signature
	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
	at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:339)
	at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:206)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:315)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:833)
	... 87 more

[10/1/20 14:39:01:892 TRT] 000000c5 FfdcProvider  W com.ibm.ws.ffdc.impl.FfdcProvider logIncident FFDC1003I: FFDC Incident emitted on /Was/IBM/WebSphere/AppServer/profiles/AppSrv01/logs/ffdc/uyg108_3_a5b084b7_20.10.01_14.39.01.8863351636182199464237.txt com.ibm.ws.websvcs.transport.http.WASAxis2Servlet.doPost 516

```

**Comment by vy** [comment]
Hey @ramazanpolat! It is very difficult to make a guess without further information. Is there a way I can reproduce the error myself? What does the classpath look? Are you sure there is only one version of `log4j2-logstash-layout` injected and/or loaded?

**Comment by ramazanpolat** [comment]
Closing since this layout is outdated.
